-- Share Links Table for public rating pages
CREATE TABLE IF NOT EXISTS share_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
    slug VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(255),
    description TEXT,
    expires_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_share_links_slug ON share_links(slug);
CREATE INDEX IF NOT EXISTS idx_share_links_category ON share_links(category_id);

-- Public Ratings Table (for share link ratings)
CREATE TABLE IF NOT EXISTS public_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_link_id BIGINT REFERENCES share_links(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
    client_name VARCHAR(255) NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_public_ratings_link ON public_ratings(share_link_id);
CREATE INDEX IF NOT EXISTS idx_public_ratings_created ON public_ratings(created_at DESC);
