-- Supabase Database Schema for Rating App

-- Create admins table
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create categories table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create ratings table
CREATE TABLE IF NOT EXISTS ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    user_ip VARCHAR(45),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_ratings_category ON ratings(category_id);
CREATE INDEX IF NOT EXISTS idx_ratings_created ON ratings(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ratings_ip_time ON ratings(user_ip, created_at DESC);

-- Insert default categories
INSERT INTO categories (name, description) VALUES
    ('General', 'General category for any feedback'),
    ('Product Quality', 'Rating for product quality'),
    ('Customer Service', 'Rating for customer service experience'),
    ('Delivery', 'Rating for delivery experience'),
    ('Value for Money', 'Rating for value and pricing')
ON CONFLICT DO NOTHING;

-- Note: To create an admin, use the API endpoint POST /api/v1/admin/create
-- with a username and password (minimum 6 characters)